### PR TITLE
Replace spaces with dashes in categories url

### PR DESCRIPTION
**Pull request by cleicar**
This PR is related to issue #105

### CODE REVIEW

**Comment by mauro-oto** [comment]
@cleicar @etagwerker we should also ensure that the old URLs continue to work, otherwise there will be plenty of 404's.

**Comment by cleicar** [comment]
@mauro-oto by pushing the re-builded files the URLs are not automatically regenerated?

**Comment by mauro-oto** [comment]
@cleicar sorry, I'm not sure what you meant. The article URLs come from the generated .html filenames. If you run `bundle exec jekyll build` these should regenerate.

**Comment by cleicar** [comment]
@mauro-oto @etagwerker How can we ensure that all links is gonna work? Maybe add some redirect ? Is it possible with jekyll?

**Comment by etagwerker** [comment]
@cleicar I think you will need to add a plugin for that. Maybe this one: https://github.com/jekyll/jekyll-redirect-from

**Comment by cleicar** [comment]
After evaluate this problem we came to conclusion that the best solution is not use space in category names. Therefore we can close this issue.

@etagwerker what do you think?

**Comment by etagwerker** [comment]
@cleicar Yes, I think that's a good idea. Thanks!

**Pull request closed without merging**
